apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegram-proxy
  name: telegram-proxy
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: telegram-proxy
